2024-03-31T13:58:38 {"cpu": 0.11865234375, "cpu_total": 4, "cpu_usage": 0.0296630859375, "memory": 3387.0, "memory_total": 15986.0, "memory_usage": 0.21187288877768046, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893518.781397, "uuid": "22195b3af9e44dcaba9ec5d8dd2fa026"}
2024-03-31T13:58:38 {"cpu": 0.11865234375, "cpu_total": 4, "cpu_usage": 0.0296630859375, "memory": 3422.0, "memory_total": 15986.0, "memory_usage": 0.2140623045164519, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893518.930773, "uuid": "368d2f619ab24e47ae14d8ca399fb972"}
2024-03-31T13:58:38 {"block_run_id": 16, "block_uuid": "load_from_api", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Execute PipelineRun 6, BlockRun 16: pipeline etl block load_from_api", "timestamp": 1711893518.978915, "uuid": "5fb4bfbb64fe4b31a8786eac2954f2a1"}
2024-03-31T13:58:49 {"cpu": 0.11669921875, "cpu_total": 4, "cpu_usage": 0.0291748046875, "memory": 3538.0, "memory_total": 15986.0, "memory_usage": 0.22131865382209434, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893529.069277, "uuid": "965639122c7a4dbc92c270b618543561"}
2024-03-31T13:58:58 {"cpu": 0.11474609375, "cpu_total": 4, "cpu_usage": 0.0286865234375, "memory": 3570.0, "memory_total": 15986.0, "memory_usage": 0.22332040535468534, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893538.207959, "uuid": "fea5c15b65534553927a0f8076ed53b5"}
2024-03-31T13:59:08 {"cpu": 0.11865234375, "cpu_total": 4, "cpu_usage": 0.0296630859375, "memory": 3623.0, "memory_total": 15986.0, "memory_usage": 0.22663580633053923, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893548.33668, "uuid": "e7c6280025a742bd95f7722cf731b706"}
2024-03-31T13:59:18 {"cpu": 0.11669921875, "cpu_total": 4, "cpu_usage": 0.0291748046875, "memory": 3642.0, "memory_total": 15986.0, "memory_usage": 0.22782434630301515, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893558.465834, "uuid": "bc8e3006772f4bac87803ed95c0d30fd"}
2024-03-31T13:59:28 {"cpu": 0.11474609375, "cpu_total": 4, "cpu_usage": 0.0286865234375, "memory": 3676.0, "memory_total": 15986.0, "memory_usage": 0.2299512073063931, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893568.598355, "uuid": "78358ea098d84fefa6f10eb69691c1ba"}
2024-03-31T13:59:38 {"cpu": 0.11865234375, "cpu_total": 4, "cpu_usage": 0.0296630859375, "memory": 4098.0, "memory_total": 15986.0, "memory_usage": 0.25634930564243713, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893578.762616, "uuid": "d3da5f8278d4439db457741cb0c40d86"}
2024-03-31T13:59:40 {"block_run_id": 16, "block_uuid": "load_from_api", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "BlockRun 16 (block_uuid: load_from_api) completes.", "timestamp": 1711893580.726624, "uuid": "ac25b6e52259407689c8948437a192ad"}
2024-03-31T13:59:48 {"cpu": 0.11669921875, "cpu_total": 4, "cpu_usage": 0.0291748046875, "memory": 3412.0, "memory_total": 15986.0, "memory_usage": 0.2134367571625172, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893588.895458, "uuid": "08f19690238f46a78d715313b7293efc"}
2024-03-31T13:59:49 {"block_run_id": 17, "block_uuid": "transform_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Execute PipelineRun 6, BlockRun 17: pipeline etl block transform_data", "timestamp": 1711893589.068427, "uuid": "67e5a9f781294017aea096a91defae06"}
2024-03-31T13:59:56 {"block_run_id": 17, "block_uuid": "transform_data", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "BlockRun 17 (block_uuid: transform_data) completes.", "timestamp": 1711893596.625991, "uuid": "0309ef0917404e3d9cefa2346ca7f36a"}
2024-03-31T13:59:59 {"cpu": 0.12646484375, "cpu_total": 4, "cpu_usage": 0.0316162109375, "memory": 3429.0, "memory_total": 15986.0, "memory_usage": 0.21450018766420617, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893599.084583, "uuid": "58d5f9abf4134ede86e59275e35d0e3f"}
2024-03-31T13:59:59 {"block_run_id": 18, "block_uuid": "export_to_gcs", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Execute PipelineRun 6, BlockRun 18: pipeline etl block export_to_gcs", "timestamp": 1711893599.261558, "uuid": "e6c8197143ab4332b7ff9024650d7ef0"}
2024-03-31T14:00:00 {"block_run_id": 18, "block_uuid": "export_to_gcs", "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "EXCEPTION", "message": "BlockRun 18 (block_uuid: export_to_gcs) failed.", "timestamp": 1711893600.436687, "uuid": "23712070b6e14ef4a68e34941e280c49", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1257, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1166, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1472, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1628, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1667, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 40, in export_data_to_google_cloud_storage\nNameError: name 'pa' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1652, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1161, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'pa' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1257, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1166, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1472, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1628, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1667, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 40, in export_data_to_google_cloud_storage
NameError: name 'pa' is not defined
2024-03-31T14:00:09 {"cpu": 0.12451171875, "cpu_total": 4, "cpu_usage": 0.0311279296875, "memory": 3433.0, "memory_total": 15986.0, "memory_usage": 0.21475040660578007, "pipeline_run_id": 6, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "9c47d0d89432", "level": "INFO", "message": "Pipeline etl for run 6 in schedule 1 is alive.", "timestamp": 1711893609.28094, "uuid": "09e335bf1c144367a14ec560c7ebfa4d"}
